name: Tests
on: [push, pull_request]
env:
  CI: true
  NODE: 12.x

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:cov

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
